---
- name: Configure Vector
  template:
    src=templates/vector.toml.j2
    dest=/opt/vector-x86_64-unknown-linux-musl/config/vector.yaml
  register: out
  changed_when: false

- debug:
    var: out