---
#- name: Install vector packages
#  become: true
#  become_user: root
#  ansible.builtin.dnf:
#    name:
#      - vector-{{ vector_rpm_version }}.x86_64.rpm
#    disable_gpg_check: true
#  notify: Restart vector service

#- name: Install vector packages
#  become: true
#  become_user: root
#  ansible.builtin.yum:
#    use_backend: yum4
#    name: "https://yum.vector.dev/stable/vector-0/x86_64/vector-{{ vector_rpm_version }}.x86_64.rpm"
#    disable_gpg_check: true
#    state: present
#  with_items: "{{ vector_version }}"

  - name: Install vector packages
#  become: true
#  become_user: root
  ansible.builtin.apt:
    deb: " https://apt.vector.dev/pool/v/ve/{{ vector_version }}-1_amd64.deb"
  with_items: "{{ vector_version }}"