---
#- include_tasks: create.yml
#  tags: [always]
#- include_tasks: download.yml
#  tags: [always]
- include_tasks: extract.yml
  tags: [always]
- include_tasks: configure.yml
  tags: [always]
- include_tasks: run.yml
  tags: [always]
