---
- name: Run Vector
  shell: nohup /opt/vector-x86_64-unknown-linux-musl/bin/vector --config /opt/vector-x86_64-unknown-linux-musl/config/vector.yaml --watch-config &
  register: out
  changed_when: false

- debug:
    var: out